### ISSUE TITLE
Allow to pass options to cors

### ISSUE THREAD

**Issue by pradel** [js-accounts/rest#8]

**Comment by TimMikeladze** [comment]
@pradel could you elaborate on this?

**Comment by pradel** [comment]
Maybe you want to only accept some domains in you cors config [here](https://github.com/js-accounts/rest/blob/master/packages/express/src/accountsExpress.js#L20).

**Comment by TimMikeladze** [comment]
Ah I see. what are your thoughts about having that config passed to `accountsExpress` rather than being defined via`AccountsServer.config`

**Comment by pradel** [comment]
Yeah may be better, or maybe let the user handle cors on his express server and don't set cors at all?

**Comment by TimMikeladze** [comment]
Good idea, I don't see why not. We should provide some documentation though.
